
export const MODELS = {
  Title: {
    path: "/models/text/title.glb",
    defaultPosition: [0, 0.6, 0],
    defaultScale: [5, 5, 5],
  },
  Loading: {
    path: "/models/text/loading.glb",
    defaultPosition: [0, 0, 0],
    defaultScale: [0.15, 0.15, 0.15],
  },
  Desk: {
    path: "/models/back/desk.glb",
    defaultPosition: [0, 0, 0],
    defaultScale: [0.005, 0.005, 0.005],
  },
  Desk2: {
    path: "/models/desk2/desk.glb",
    defaultPosition: [0, -8.9, 0],
    defaultScale: [2.4, 2.4, 2.4],
  },
  Camera: {
    path: "/models/camera/camera.glb",
    defaultPosition: [0, 0, 0],
    defaultScale: [0.005, 0.005, 0.005],
  },
  Finish: {
    path: "/models/finish.glb",
    defaultPosition: [0, 0, 0],
    defaultScale: [0.8, 0.8, 0.8],
  },
  Start: {
    path: "/models/start.glb",
    defaultPosition: [0, 0, 0],
    defaultScale: [0.5, 0.5, 0.5],
  },
  Arrow1: {
    path: "/models/arrow1.glb",
    defaultPosition: [0, 0, 0],
    defaultScale: [0.8, 0.8, 0.8],
  },
  Arrow2: {
    path: "/models/arrow2.glb",
    defaultPosition: [0, 0, 0],
    defaultScale: [0.18, 0.18, 0.18],
  },
  
}

export const CAKES = {
  Circle: {
    path: "/models/cake/circle.glb",
    defaultPosition: [0, -1.8, 0],
    defaultScale: [0.25, 0.25, 0.25],
  },
  Square: {
    path: "/models/cake/square.glb",
    defaultPosition: [0, -2, 0],
    defaultScale: [0.28, 0.28, 0.28],
  },
  Triangle: {
    path: "/models/cake/triangle.glb",
    defaultPosition: [0, -2, 0],
    defaultScale: [0.23, 0.23, 0.23],
  },
};

export const PLATE = {
  Plate: {
    path: "/models/plate/plate.glb",
    defaultPosition: [0, 0, 0],
    defaultScale: [3, 3, 3],
  },
};

export const CHRISTMAS = {
  Bag: {
    index: 0,
    path: "/models/item/christmas/bag.glb",
    defaultPosition: [0, 0, 0],
    defaultScale: [1.1, 1.1, 1.1],
    defaultRotation: [0, 0, 0],
  },
  BatWings: {
    index: 1,
    path: "/models/item/christmas/batWings.glb",
    defaultPosition: [-0.5, 0, 0],
    defaultScale: [1.4, 1.4, 1.4],
    defaultRotation: [0, 0, 0],
  },
  Bell: {
    index: 2,
    path: "/models/item/christmas/bell.glb",
    defaultPosition: [0, 0, 0],
    defaultScale: [1.1, 1.1, 1.1],
    defaultRotation: [0, 0, 0],
  },
  Broom: {
    index: 3,
    path: "/models/item/christmas/broom.glb",
    defaultPosition: [0.1, 0, 0],
    defaultScale: [1.1, 1.1, 1.1],
    defaultRotation: [0, 0, 0],
  },
  Candle1: {
    index: 4,
    path: "/models/item/christmas/candle1.glb",
    defaultPosition: [0.1, 0, 0],
    defaultScale: [1.2, 1.2, 1.2],
    defaultRotation: [0, 0, 0],
  },
  Candle2: {
    index: 5,
    path: "/models/item/christmas/candle2.glb",
    defaultPosition: [-0.05, 0, 0],
    defaultScale: [1.2, 1.2, 1.2],
    defaultRotation: [0, 0, 0],
  },
  Candy: {
    index: 6,
    path: "/models/item/christmas/candy.glb",
    defaultPosition: [-0.3, 0.1, 0],
    defaultScale: [1.3, 1.3, 1.3],
    defaultRotation: [0, 0, 0],
  },
  Coffin: {
    index: 7,
    path: "/models/item/christmas/coffin.glb",
    defaultPosition: [0, 0.2, 0],
    defaultScale: [1.1, 1.1, 1.1],
    defaultRotation: [0, 0, 0],
  },
  Cross: {
    index: 8,
    path: "/models/item/christmas/cross.glb",
    defaultPosition: [-0.2, -0.1, 0],
    defaultScale: [1.1, 1.1, 1.1],
    defaultRotation: [0, 0, 0],
  },
  Decoration: {
    index: 9,
    path: "/models/item/christmas/decoration.glb",
    defaultPosition: [-0.3, 0, 0],
    defaultScale: [1.15, 1.15, 1.15],
    defaultRotation: [0, 0, 0],
  },
  Ghost: {
    index: 10,
    path: "/models/item/christmas/ghost.glb",
    defaultPosition: [-0.2, -0.1, 0],
    defaultScale: [1.2, 1.2, 1.2],
    defaultRotation: [0, 0, 0],
  },
  SantaHat: {
    index: 11,
    path: "/models/item/christmas/santaHat.glb",
    defaultPosition: [0, 0, 0],
    defaultScale: [1.1, 1.1, 1.1],
    defaultRotation: [0, 0, 0],
  },
  Sled: {
    index: 12,
    path: "/models/item/christmas/sled.glb",
    defaultPosition: [0.3, 0.2, 0],
    defaultScale: [1.3, 1.3, 1.3],
    defaultRotation: [0, 0, 0],
  },
  SnowFlake: {
    index: 13,
    path: "/models/item/christmas/snowFlake.glb",
    defaultPosition: [0.1, -0.2, 0],
    defaultScale: [1.1, 1.1, 1.1],
    defaultRotation: [0, 0, 0],
  },
  SnowMan: {
    index: 14,
    path: "/models/item/christmas/snowMan.glb",
    defaultPosition: [0, -0.4, 0],
    defaultScale: [1.5, 1.5, 1.5],
    defaultRotation: [0, 0, 0],
  },
  Socks: {
    index: 15,
    path: "/models/item/christmas/socks.glb",
    defaultPosition: [-0.1, -0.1, 0],
    defaultScale: [1, 1, 1],
    defaultRotation: [0, 0, 0],
  },
  Tree1: {
    index: 16,
    path: "/models/item/christmas/tree1.glb",
    defaultPosition: [-0.2, -0.1, 0],
    defaultScale: [1.4, 1.4, 1.4],
    defaultRotation: [0, 0, 0],
  },
  Tree2: {
    index: 17,
    path: "/models/item/christmas/tree2.glb",
    defaultPosition: [-0.2, -0.1, 0],
    defaultScale: [1.35, 1.35, 1.35],
    defaultRotation: [0, 0, 0],
  },
};

export const FOOD = {
  Almond: {
    index: 0,
    path: "/models/item/food/almond.glb",
    defaultPosition: [0, -0.1, 0],
    defaultScale: [1.1, 1.1, 1.1],
    defaultRotation: [0, 0, 0],
  },
  Apple: {
    index: 1,
    path: "/models/item/food/apple.glb",
    defaultPosition: [0, -0.1, 0],
    defaultScale: [1.1, 1.1, 1.1],
    defaultRotation: [0, 0, 0],
  },
  Banana: {
    index: 2,
    path: "/models/item/food/banana.glb",
    defaultPosition: [0, 0, 0],
    defaultScale: [1.2, 1.2, 1.2],
    defaultRotation: [0, 0, 0],
  },
  Blueberry: {
    index: 3,
    path: "/models/item/food/blueberry.glb",
    defaultPosition: [0.2, 0.4, 0],
    defaultScale: [1.2, 1.2, 1.2],
    defaultRotation: [0, 0, 0],
  },
  Broccoli: {
    index: 4,
    path: "/models/item/food/broccoli.glb",
    defaultPosition: [0, -0.4, 0],
    defaultScale: [1.2, 1.2, 1.2],
    defaultRotation: [0, 0, 0],
  },
  Carrot: {
    index: 5,
    path: "/models/item/food/carrot.glb",
    defaultPosition: [0.1, -0.25, 0],
    defaultScale: [1.2, 1.2, 1.2],
    defaultRotation: [0, 0, 0],
  },
  Cheese: {
    index: 6,
    path: "/models/item/food/cheese.glb",
    defaultPosition: [-0.1, 0.4, 0],
    defaultScale: [1, 1, 1],
    defaultRotation: [Math.PI / 4, 0, 0],
  },
  Cherries: {
    index: 7,
    path: "/models/item/food/cherries.glb",
    defaultPosition: [-0.2, -0.1, 0],
    defaultScale: [1.05, 1.05, 1.05],
    defaultRotation: [0, 0, 0],
  },
  ChocolateBar: {
    index: 8,
    path: "/models/item/food/chocolateBar.glb",
    defaultPosition: [-0.6, 0, 0],
    defaultScale: [1.15, 1.15, 1.15],
    defaultRotation: [0, 0, - Math.PI / 8],
  },
  Donut: {
    index: 9,
    path: "/models/item/food/donut.glb",
    defaultPosition: [0, 0.9, 0],
    defaultScale: [1, 1, 1],
    defaultRotation: [Math.PI / 2, 0, Math.PI / 4],
  },
  EggPlant: {
    index: 10,
    path: "/models/item/food/eggPlant.glb",
    defaultPosition: [0, -0.1, 0],
    defaultScale: [1.2, 1.2, 1.2],
    defaultRotation: [0, 0, 0],
  },
  FriedEgg: {
    index: 11,
    path: "/models/item/food/friedEgg.glb",
    defaultPosition: [0, 0.9, 0],
    defaultScale: [1.3, 1.3, 1.3],
    defaultRotation: [Math.PI / 2, 0, 0],
  },
  FriedShrimp: {
    index: 12,
    path: "/models/item/food/friedShrimp.glb",
    defaultPosition: [0, -0.2, 0],
    defaultScale: [1.2, 1.2, 1.2],
    defaultRotation: [0, 0, 0],
  },
  Grapes: {
    index: 13,
    path: "/models/item/food/grapes.glb",
    defaultPosition: [0, -0.4, 0],
    defaultScale: [1.4, 1.4, 1.4],
    defaultRotation: [0, 0, 0],
  },
  Lemon: {
    index: 14,
    path: "/models/item/food/lemon.glb",
    defaultPosition: [0, 0.1, 0],
    defaultScale: [1.3, 1.3, 1.3],
    defaultRotation: [0, 0, 0],
  },
  Meat: {
    index: 15,
    path: "/models/item/food/meat.glb",
    defaultPosition: [0, -0.2, 0],
    defaultScale: [1.3, 1.3, 1.3],
    defaultRotation: [0, 0, 0],
  },
  Mushroom: {
    index: 16,
    path: "/models/item/food/mushroom.glb",
    defaultPosition: [-0.1, 0, 0],
    defaultScale: [1.2, 1.2, 1.2],
    defaultRotation: [0, 0, 0],
  },
  Pear: {
    index: 17,
    path: "/models/item/food/pear.glb",
    defaultPosition: [0, -0.1, 0],
    defaultScale: [1.1, 1.1, 1.1],
    defaultRotation: [0, 0, 0],
  },
  Tomato: {
    index: 18,
    path: "/models/item/food/tomato.glb",
    defaultPosition: [-0.2, -0.1, 0],
    defaultScale: [1.2, 1.2, 1.2],
    defaultRotation: [0, 0, 0],
  },
  WaterMelon: {
    index: 19,
    path: "/models/item/food/waterMelon.glb",
    defaultPosition: [0, 0, 0],
    defaultScale: [1.05, 1.05, 1.05],
    defaultRotation: [0, 0, 0],
  },
};

export const HALLOWEEN = {
  Abandonment: {
    index: 0,
    path: "/models/item/halloween/abandonment.glb",
    defaultPosition: [0, -0.3, 0],
    defaultScale: [1.3, 1.3, 1.3],
    defaultRotation: [0, 0, 0],
  },
  Bone: {
    index: 1,
    path: "/models/item/halloween/bone.glb",
    defaultPosition: [-0.1, -0.1, 0],
    defaultScale: [1.2, 1.2, 1.2],
    defaultRotation: [0, 0, 0],
  },
  Grave: {
    index: 2,
    path: "/models/item/halloween/grave.glb",
    defaultPosition: [-0.2, 0, 0],
    defaultScale: [1.4, 1.4, 1.4],
    defaultRotation: [0, 0, 0],
  },
  Pumpkin: {
    index: 3,
    path: "/models/item/halloween/pumpkin.glb",
    defaultPosition: [0, 0, 0],
    defaultScale: [1.2, 1.2, 1.2],
    defaultRotation: [Math.PI / 12, 0, 0],
  },
  Skeleton: {
    index: 4,
    path: "/models/item/halloween/skeleton.glb",
    defaultPosition: [0, -0.2, 0],
    defaultScale: [1.2, 1.2, 1.2],
    defaultRotation: [0, 0, 0],
  },
  SpiderWebs: {
    index: 5,
    path: "/models/item/halloween/spiderWebs.glb",
    defaultPosition: [0.1, -0.2, 0],
    defaultScale: [1.2, 1.2, 1.2],
    defaultRotation: [0, 0, 0],
  },
  SpinyCandy: {
    index: 6,
    path: "/models/item/halloween/spinyCandy.glb",
    defaultPosition: [0.1, -0.2, 0],
    defaultScale: [1.3, 1.3, 1.3],
    defaultRotation: [0, 0, 0],
  },
  StickCandy: {
    index: 7,
    path: "/models/item/halloween/stickCandy.glb",
    defaultPosition: [0, 0, 0],
    defaultScale: [1.2, 1.2, 1.2],
    defaultRotation: [0, 0, 0],
  },
};

export const OTHER = {
  BowAndArrow: {
    index: 0,
    path: "/models/item/other/bowAndArrow.glb",
    defaultPosition: [0, -0.4, 0],
    defaultScale: [1.2, 1.2, 1.2],
    defaultRotation: [0, 0, 0],
  },
  Crown: {
    index: 1,
    path: "/models/item/other/crown.glb",
    defaultPosition: [-0.1, 0.1, 0],
    defaultScale: [1, 1, 1],
    defaultRotation: [Math.PI / 6, 0, - Math.PI / 10],
  },
  Leaf: {
    index: 2,
    path: "/models/item/other/leaf.glb",
    defaultPosition: [0, -0.3, 0],
    defaultScale: [1.1, 1.1, 1.1],
    defaultRotation: [0, 0, 0],
  },
  Star1: {
    index: 3,
    path: "/models/item/other/star1.glb",
    defaultPosition: [0, -0.1, 0],
    defaultScale: [1.3, 1.3, 1.3],
    defaultRotation: [0, 0, 0],
  },
  Star2: {
    index: 4,
    path: "/models/item/other/star2.glb",
    defaultPosition: [0, -0.1, 0],
    defaultScale: [1, 1, 1],
    defaultRotation: [0, 0, 0],
  },
  Sword: {
    index: 5,
    path: "/models/item/other/sword.glb",
    defaultPosition: [0.2, -0.1, 0],
    defaultScale: [1.2, 1.2, 1.2],
    defaultRotation: [0, 0, 0],
  },
};

export const PRESENT = {
  Present1: {
    index: 0,
    path: "/models/item/present/present1.glb",
    defaultPosition: [0.3, 0.8, 0],
    defaultScale: [0.9, 0.9, 0.9],
    defaultRotation: [Math.PI / 2, 0, 0],
  },
  Present2: {
    index: 1,
    path: "/models/item/present/present2.glb",
    defaultPosition: [0.15, 0.9, 0],
    defaultScale: [0.7, 0.7, 0.7],
    defaultRotation: [Math.PI / 2, 0, 0],
  },
  Present3: {
    index: 2,
    path: "/models/item/present/present3.glb",
    defaultPosition: [0.2, 0.8, 0],
    defaultScale: [1, 1, 1],
    defaultRotation: [Math.PI / 2, 0, 0],
  },
  Present4: {
    index: 3,
    path: "/models/item/present/present4.glb",
    defaultPosition: [0.1, 0.8, 0],
    defaultScale: [1, 1, 1],
    defaultRotation: [Math.PI / 2, 0, 0],
  },
  Present5: {
    index: 4,
    path: "/models/item/present/present5.glb",
    defaultPosition: [0.1, 0.8, 0],
    defaultScale: [1, 1, 1],
    defaultRotation: [Math.PI / 2, 0, 0],
  },
};

export const RIBON = {
  Ribon1: {
    index: 0,
    path: "/models/item/ribon/ribon1.glb",
    defaultPosition: [0, 0.9, 0],
    defaultScale: [1.3, 1.3, 1.3],
    defaultRotation: [Math.PI / 2, 0, 0],
  },
  Ribon2: {
    index: 1,
    path: "/models/item/ribon/ribon2.glb",
    defaultPosition: [0.1, 0.9, 0],
    defaultScale: [1.1, 1.1, 1.1],
    defaultRotation: [Math.PI / 2, 0, 0],
  },
  Ribon3: {
    index: 2,
    path: "/models/item/ribon/ribon3.glb",
    defaultPosition: [0, 0.9, 0],
    defaultScale: [1.3, 1.3, 1.3],
    defaultRotation: [Math.PI / 2, 0, 0],
  },
};

export const SPORTS = {
  Badminton: {
    index: 0,
    path: "/models/item/sports/badminton.glb",
    defaultPosition: [0, 0, 0],
    defaultScale: [1.5, 1.5, 1.5],
    defaultRotation: [0, 0, 0],
  },
  Barbell: {
    index: 1,
    path: "/models/item/sports/barbell.glb",
    defaultPosition: [-0.2, 0.6, 0],
    defaultScale: [1.3, 1.3, 1.3],
    defaultRotation: [0, 0, 0],
  },
  Baseball: {
    index: 2,
    path: "/models/item/sports/baseball.glb",
    defaultPosition: [0, 0.1, 0],
    defaultScale: [1, 1, 1],
    defaultRotation: [0, 0, 0],
  },
  Basketball: {
    index: 3,
    path: "/models/item/sports/basketball.glb",
    defaultPosition: [0, 0.1, 0],
    defaultScale: [1, 1, 1],
    defaultRotation: [0, 0, 0],
  },
  Bowling: {
    index: 4,
    path: "/models/item/sports/bowling.glb",
    defaultPosition: [0, 0, 0],
    defaultScale: [1.2, 1.2, 1.2],
    defaultRotation: [0, 0, 0],
  },
  Boxing: {
    index: 5,
    path: "/models/item/sports/boxing.glb",
    defaultPosition: [-0.3, 0, 0],
    defaultScale: [1.1, 1.1, 1.1],
    defaultRotation: [0, 0, 0],
  },
  Football: {
    index: 6,
    path: "/models/item/sports/football.glb",
    defaultPosition: [-0.1, -0.1, 0],
    defaultScale: [1.1, 1.1, 1.1],
    defaultRotation: [0, 0, 0],
  },
  Golfball: {
    index: 7,
    path: "/models/item/sports/golfball.glb",
    defaultPosition: [0, -0.1, 0],
    defaultScale: [1, 1, 1],
    defaultRotation: [0, 0, 0],
  },
  Golfclub: {
    index: 8,
    path: "/models/item/sports/golfclub.glb",
    defaultPosition: [-0.3, 0, 0],
    defaultScale: [1.2, 1.2, 1.2],
    defaultRotation: [0, 0, 0],
  },
  PingPong: {
    index: 9,
    path: "/models/item/sports/pingPong.glb",
    defaultPosition: [0.2, 0, 0],
    defaultScale: [1.1, 1.1, 1.1],
    defaultRotation: [0, 0, 0],
  },
  Poolball: {
    index: 10,
    path: "/models/item/sports/poolball.glb",
    defaultPosition: [-0.1, -0.1, 0],
    defaultScale: [1.05, 1.05, 1.05],
    defaultRotation: [0, 0, 0],
  },
  Racquet: {
    index: 11,
    path: "/models/item/sports/racquet.glb",
    defaultPosition: [0, 0, 0],
    defaultScale: [1.3, 1.3, 1.3],
    defaultRotation: [0, 0, 0],
  },
  Shuttlecock: {
    index: 12,
    path: "/models/item/sports/shuttlecock.glb",
    defaultPosition: [-0.3, -0.2, 0],
    defaultScale: [1.2, 1.2, 1.2],
    defaultRotation: [0, 0, 0],
  },
  Soccerball: {
    index: 13,
    path: "/models/item/sports/soccerball.glb",
    defaultPosition: [0, -0.1, 0],
    defaultScale: [1.1, 1.1, 1.1],
    defaultRotation: [0, 0, 0],
  },
  Surfboard: {
    index: 14,
    path: "/models/item/sports/surfboard.glb",
    defaultPosition: [0.1, 0, 0],
    defaultScale: [1.2, 1.2, 1.2],
    defaultRotation: [0, 0, 0],
  },
  Tennisball: {
    index: 15,
    path: "/models/item/sports/tennisball.glb",
    defaultPosition: [0, 0.1, 0],
    defaultScale: [1, 1, 1],
    defaultRotation: [0, 0, 0],
  },
  Trophy: {
    index: 16,
    path: "/models/item/sports/trophy.glb",
    defaultPosition: [-0.1, -0.2, 0],
    defaultScale: [1.2, 1.2, 1.2],
    defaultRotation: [0, 0, 0],
  },
  Volleyball: {
    index: 17,
    path: "/models/item/sports/volleyball.glb",
    defaultPosition: [0, -0.1, 0],
    defaultScale: [1.1, 1.1, 1.1],
    defaultRotation: [0, 0, 0],
  },
};

export const MAIN = {
  Candle1: {
    index: 0,
    path: "/models/main/candle1.glb",
    defaultPosition: [0.1, -0.2, 0],
    defaultScale: [1.3, 1.3, 1.3],
    defaultRotation: [0, 0, 0],
  },
  Candle2: {
    index: 1,
    path: "/models/main/candle2.glb",
    defaultPosition: [-0.2, -0.2, 0],
    defaultScale: [1.3, 1.3, 1.3],
    defaultRotation: [0, 0, 0],
  },
  StrawberryBig: {
    index: 2,
    path: "/models/main/strawberryBig.glb",
    defaultPosition: [0, 0, 0],
    defaultScale: [1, 1, 1],
    defaultRotation: [0, 0, 0],
  },
  StrawberryHalf: {
    index: 3,
    path: "/models/main/strawberryHalf.glb",
    defaultPosition: [0, 0, 0],
    defaultScale: [1, 1, 1],
    defaultRotation: [0, 0, 0],
  },
  StrawberryQuarter: {
    index: 4,
    path: "/models/main/strawberryQuarter.glb",
    defaultPosition: [-0.4, 1, 0],
    defaultScale: [1, 1, 1],
    defaultRotation: [Math.PI / 16, Math.PI / 8, - Math.PI / 2],
  },
  Whip: {
    index: 5,
    path: "/models/main/whip.glb",
    defaultPosition: [0, 0.2, 0],
    defaultScale: [1, 1, 1],
    defaultRotation: [0, 0, 0],
  },
};

export const CUSTOM = {
  Chocolate: {
    index: 0,
    path: "/models/custom/chocolate.glb",
    defaultPosition: [0, -2, 0],
    defaultScale: [0.8, 0.8, 0.8],
  },
  Pumpkin: {
    index: 1,
    path: "/models/custom/pumpkin.glb",
    defaultPosition: [0, -2, 0],
    defaultScale: [0.8, 0.8, 0.8],
  },
  Snowman: {
    index: 2,
    path: "/models/custom/snowman.glb",
    defaultPosition: [0, -2, 0],
    defaultScale: [0.8, 0.8, 0.8],
  },
};

export const BUTTON = {
  changeModel: {
    path: "/models/button/changeModel.glb",
    defaultPosition: [0, 0, 0],
    defaultScale: [0.8, 0.8, 0.8],
  },
  Delete: {
    path: "/models/button/delete.glb",
    defaultPosition: [0, 0, 0],
    defaultScale: [0.8, 0.8, 0.8],
  },
  Share1: {
    path: "/models/button/share1.glb",
    defaultPosition: [0, -2, 0],
    defaultScale: [0.8, 0.8, 0.8],
  },
  Share2: {
    path: "/models/button/share2.glb",
    defaultPosition: [0, -2, 0],
    defaultScale: [0.8, 0.8, 0.8],
  },
  Move: {
    path: "/models/button/move.glb",
    defaultPosition: [0, 0, 0],
    defaultScale: [0.8, 0.8, 0.8],
  },
  Rotate: {
    path: "/models/button/rotate.glb",
    defaultPosition: [0, 0, 0],
    defaultScale: [0.8, 0.8, 0.8],
  },
  Scale: {
    path: "/models/button/scale.glb",
    defaultPosition: [0, 0, 0],
    defaultScale: [0.8, 0.8, 0.8],
  },
};

export const TITLE1 = {
  SantaHat: {
    index: 0,
    path: "/models/item/christmas/santaHat.glb",
    defaultPosition: [0, 0, 0],
    defaultScale: [1.1, 1.1, 1.1],
    defaultRotation: [0, 0, 0],
  },
  Tree2: {
    index: 1,
    path: "/models/item/christmas/tree2.glb",
    defaultPosition: [-0.2, -0.1, 0],
    defaultScale: [1.35, 1.35, 1.35],
    defaultRotation: [0, 0, 0],
  },
  StrawberryBig: {
    index: 2,
    path: "/models/main/strawberryBig.glb",
    defaultPosition: [0, 0, 0],
    defaultScale: [1, 1, 1],
    defaultRotation: [0, 0, 0],
  },
  StrawberryHalf: {
    index: 3,
    path: "/models/main/strawberryHalf.glb",
    defaultPosition: [0, 0, 0],
    defaultScale: [1, 1, 1],
    defaultRotation: [0, 0, 0],
  },
  WaterMelon: {
    index: 4,
    path: "/models/item/food/waterMelon.glb",
    defaultPosition: [0, 0, 0],
    defaultScale: [1.05, 1.05, 1.05],
    defaultRotation: [0, 0, 0],
  },
  Carrot: {
    index: 5,
    path: "/models/item/food/carrot.glb",
    defaultPosition: [0.1, -0.25, 0],
    defaultScale: [1.2, 1.2, 1.2],
    defaultRotation: [0, 0, 0],
  },
  Meat: {
    index: 6,
    path: "/models/item/food/meat.glb",
    defaultPosition: [0, -0.2, 0],
    defaultScale: [1.3, 1.3, 1.3],
    defaultRotation: [0, 0, 0],
  },
  Lemon: {
    index: 7,
    path: "/models/item/food/lemon.glb",
    defaultPosition: [0, 0.1, 0],
    defaultScale: [1.3, 1.3, 1.3],
    defaultRotation: [0, 0, 0],
  },
  Grapes: {
    index: 8,
    path: "/models/item/food/grapes.glb",
    defaultPosition: [0, -0.4, 0],
    defaultScale: [1.4, 1.4, 1.4],
    defaultRotation: [0, 0, 0],
  },
  Almond: {
    index: 9,
    path: "/models/item/food/almond.glb",
    defaultPosition: [0, -0.1, 0],
    defaultScale: [1.1, 1.1, 1.1],
    defaultRotation: [0, 0, 0],
  },
  Cheese: {
    index: 10,
    path: "/models/item/food/cheese.glb",
    defaultPosition: [-0.1, 0.4, 0],
    defaultScale: [1, 1, 1],
    defaultRotation: [Math.PI / 4, 0, 0],
  },
  Ghost: {
    index: 11,
    path: "/models/item/christmas/ghost.glb",
    defaultPosition: [-0.2, -0.1, 0],
    defaultScale: [1.2, 1.2, 1.2],
    defaultRotation: [0, 0, 0],
  },
  SnowFlake: {
    index: 12,
    path: "/models/item/christmas/snowFlake.glb",
    defaultPosition: [0.1, -0.2, 0],
    defaultScale: [1.1, 1.1, 1.1],
    defaultRotation: [0, 0, 0],
  },
  Tree1: {
    index: 13,
    path: "/models/item/christmas/tree1.glb",
    defaultPosition: [-0.2, -0.1, 0],
    defaultScale: [1.4, 1.4, 1.4],
    defaultRotation: [0, 0, 0],
  },
  SnowMan: {
    index: 14,
    path: "/models/item/christmas/snowMan.glb",
    defaultPosition: [0, -0.4, 0],
    defaultScale: [1.5, 1.5, 1.5],
    defaultRotation: [0, 0, 0],
  },
  Candle2: {
    index: 15,
    path: "/models/item/christmas/candle2.glb",
    defaultPosition: [-0.05, 0, 0],
    defaultScale: [1.2, 1.2, 1.2],
    defaultRotation: [0, 0, 0],
  },
  Candy: {
    index: 16,
    path: "/models/item/christmas/candy.glb",
    defaultPosition: [-0.3, 0.1, 0],
    defaultScale: [1.3, 1.3, 1.3],
    defaultRotation: [0, 0, 0],
  },
};

export const TITLE2 = {
  Whip: {
    index: 0,
    path: "/models/main/whip.glb",
    defaultPosition: [0, 0.2, 0],
    defaultScale: [1, 1, 1],
    defaultRotation: [0, 0, 0],
  },
  Shuttlecock: {
    index: 1,
    path: "/models/item/sports/shuttlecock.glb",
    defaultPosition: [0.4, -0.2, 0],
    defaultScale: [1.2, 1.2, 1.2],
    defaultRotation: [0, 0, 0],
  },
  Basketball: {
    index: 2,
    path: "/models/item/sports/basketball.glb",
    defaultPosition: [0, 0.1, 0],
    defaultScale: [1, 1, 1],
    defaultRotation: [0, 0, 0],
  },
  Volleyball: {
    index: 3,
    path: "/models/item/sports/volleyball.glb",
    defaultPosition: [0, -0.1, 0],
    defaultScale: [1.1, 1.1, 1.1],
    defaultRotation: [0, 0, 0],
  },
  Soccerball: {
    index: 4,
    path: "/models/item/sports/soccerball.glb",
    defaultPosition: [0, -0.1, 0],
    defaultScale: [1.1, 1.1, 1.1],
    defaultRotation: [0, 0, 0],
  },
  Baseball: {
    index: 5,
    path: "/models/item/sports/baseball.glb",
    defaultPosition: [0, 0.1, 0],
    defaultScale: [1, 1, 1],
    defaultRotation: [0, 0, 0],
  },
  StickCandy: {
    index: 6,
    path: "/models/item/halloween/stickCandy.glb",
    defaultPosition: [0, 0, 0],
    defaultScale: [1.2, 1.2, 1.2],
    defaultRotation: [0, 0, 0],
  },
  SpiderWebs: {
    index: 7,
    path: "/models/item/halloween/spiderWebs.glb",
    defaultPosition: [0.5, -0.2, 0],
    defaultScale: [1.2, 1.2, 1.2],
    defaultRotation: [0, 0, 0],
  },
  Skeleton: {
    index: 8,
    path: "/models/item/halloween/skeleton.glb",
    defaultPosition: [0, -0.2, 0],
    defaultScale: [1.2, 1.2, 1.2],
    defaultRotation: [0, 0, 0],
  },
  Bone: {
    index: 9,
    path: "/models/item/halloween/bone.glb",
    defaultPosition: [-0.1, -0.1, 0],
    defaultScale: [1.2, 1.2, 1.2],
    defaultRotation: [0, 0, 0],
  },
  Coffin: {
    index: 10,
    path: "/models/item/christmas/coffin.glb",
    defaultPosition: [0, 0.2, 0],
    defaultScale: [1.1, 1.1, 1.1],
    defaultRotation: [0, 0, 0],
  },
  SpinyCandy: {
    index: 11,
    path: "/models/item/halloween/spinyCandy.glb",
    defaultPosition: [-0.3, -0.2, 0],
    defaultScale: [1.3, 1.3, 1.3],
    defaultRotation: [0, 0, 0],
  },
  Pumpkin: {
    index: 12,
    path: "/models/item/halloween/pumpkin.glb",
    defaultPosition: [-0.3, 0, 0],
    defaultScale: [1.2, 1.2, 1.2],
    defaultRotation: [Math.PI / 12, 0, 0],
  },
  Crown: {
    index: 13,
    path: "/models/item/other/crown.glb",
    defaultPosition: [-0.1, 0.1, 0],
    defaultScale: [1, 1, 1],
    defaultRotation: [Math.PI / 6, 0, - Math.PI / 10],
  },
  Leaf: {
    index: 14,
    path: "/models/item/other/leaf.glb",
    defaultPosition: [0, -0.3, 0],
    defaultScale: [1.1, 1.1, 1.1],
    defaultRotation: [0, 0, 0],
  },
  Star1: {
    index: 15,
    path: "/models/item/other/star1.glb",
    defaultPosition: [0, -0.1, 0],
    defaultScale: [1.3, 1.3, 1.3],
    defaultRotation: [0, 0, 0],
  },
  Star2: {
    index: 16,
    path: "/models/item/other/star2.glb",
    defaultPosition: [0, -0.1, 0],
    defaultScale: [1, 1, 1],
    defaultRotation: [0, 0, 0],
  },
};

